spring:
#  profiles:
#    active: test

  logging:
    level:
      root: INFO
      org.springframework.web: DEBUG
      org.springframework.security: INFO

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  datasource:
    url: jdbc:postgresql://localhost:5432/zombie
    driver-class-name: org.postgresql.Driver
    username: makisekurisu
    password: abcd1234


  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true

# ??
oauth:
  kakao:
    client_id: 920865d3fcdbfd024c9e2f35b102beb6
    redirect_uri: http://localhost:3000/oauth/redirected/kakao
    client_secret: dXIKF4iENKboF2RGWERWSgOLZwRRbfQ4
    scope: profile_nickname, profile_image, account_email
  naver:
    client_id: tsCjaf_Sguy3on43jxmt
    redirect_uri: http://localhost:3000/oauth/redirected/naver
    client_secret: F5BCjIhXHv
    scope:

jwt:
  header: Authorization
  secret: a2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbQ==
  token-validity-in-seconds: 86400000

server:
  port: 7070